-- Authorized 2026-09-27. Additive only; preserve historical rows.
-- Backup: expenses_backup_20260927_amounts_v2, restored and compared: 134 rows, 0 differences.
ALTER TABLE `mon-projet-data-2sg.m3s_2sg.expenses`
  ADD COLUMN IF NOT EXISTS ORIGINAL_CURRENCY STRING,
  ADD COLUMN IF NOT EXISTS TOTAL_PAID NUMERIC,
  ADD COLUMN IF NOT EXISTS PRINCIPAL NUMERIC,
  ADD COLUMN IF NOT EXISTS FEES NUMERIC,
  ADD COLUMN IF NOT EXISTS RECIPIENT_CURRENCY STRING,
  ADD COLUMN IF NOT EXISTS RECIPIENT_AMOUNT NUMERIC,
  ADD COLUMN IF NOT EXISTS CONVERSION_SOURCE STRING,
  ADD COLUMN IF NOT EXISTS AMOUNT_CONTRACT_VERSION INT64;
